// <auto-generated />
using System;
using ETR.Nine.Services.Forex.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETR.Nine.Services.Forex.Infrastructure.Migrations
{
    [DbContext(typeof(ForexDbContext))]
    partial class ForexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ETR.Nine.Services.Forex.Domain.Entity.ForexRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("BaseCurrency");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("DATE")
                        .HasColumnName("DateCreated");

                    b.Property<decimal>("Rate")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("Rates");

                    b.HasKey("Id");

                    b.ToTable("ForexRates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
